### ISSUE TITLE
WBS i PERT za MinecraftSim

### ISSUE THREAD

**Issue by Deno234** [R5C-V15T6AMD5S/Unity-GameHub#9]
Potrebno je izraditi **WBS** i **PERT** dijagram za igricu **MinecraftSim**. Njih je potrebno postaviti u dokumentaciju (Wiki).

**Comment by Deno234** [comment]
Predložen PERT dijagram:
![PERT](https://github.com/R5C-V15T6AMD5S/Unity-GameHub/assets/98615170/d236853a-2ac8-4eee-931e-ba4a9983f06c)

**Comment by LukaViljusic** [comment]
Predložen WBS dijagram:
<img width="1353" alt="WBS" src="https://github.com/R5C-V15T6AMD5S/Unity-GameHub/assets/94178688/96acaefd-85b2-4f65-b445-017022872ca4">
